name: Renovate Config Validator

on:
  pull_request:
    paths:
      - './renovate.json'

permissions: {}

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.23.1 # LTS
      - name: Validate Renovate config
        run: npx -p renovate --yes renovate-config-validator
